- creating-and-depoying-web-app.md
> Documentation on creating and deploying a simple web application

- cloud_computing.md
> DONE: Write a simple documentation on Cloud Computing #1

- Documentation on CSS transforms & transitions #19
@captain-sal (first of all I am really soory if I have tagged and commented you a lot ,this platform is new for me ,i am exploring )
this is the plagiarism checker report ,as explanation for CSS is very common, nothing so unique in explaining simple properties but i tried to explain everything in my words. I hope it works.
> Create  Documentation on CSS transforms & transitions #19

- integrating_auth0.md
> Integrating Auth0 for User Authentication in Web Applications

- gemini.md
Hello team,
I've completed the documentation for Gemini ai covering definition,features and models. The content is organized for clarity, and I've incorporated examples to facilitate understanding. Please review the documentation and share any suggestions or corrections.
issue: #28 
Appreciate your time and feedback.
[VenusCh001]
> Gemini ai documentation 

- Documentation on Web Development #14
> Create Documentation on Web Development #14

- Documentation on CyberSecurity #50 by priyamina.md
@captain-sal work submitted ✅please merge.
>  Documentation on CyberSecurity #50 by priyamina

- documentation on cloud computing.md
documentation on cloud computing(by priya mina) completed ✅
> documentation on cloud computing(by priya mina).md

- Documentation on CSS Flexbox and Grid Layout. #5(by priya mina).md
>  Documentation on CSS Flexbox and Grid Layout(by priya mina)

- DSA technical paper on RECURSION #41 by priyamina.md
@captain-sal  please merge this.
>  DSA technical paper on RECURSION #41 by priyamina

- Write a documentation on getting started with UI UX #2 by priyamina.md
>  a documentation on getting started with UI UX #2 by priyamina

- Documentation on OOPS(object oriented programming) #51 by priyamina.md
> Documentation on OOPS(object oriented programming) #51 by priyamina

- Documentation on basics of dart in flutter.md
I have created a documentation that covers the basic concepts of dart used in flutter. 
It includes an introduction to Flutter and dart and then the basic syntax and operations used in dart with code.
> Documentation on basics of Dart (Flutter)

- Documentation writing on AI in coding life #34 by priyamina.md
@captain-sal done✅ please merge
>  Documentation writing on AI in coding life #34 by priyamina.md

- Introduction to Docker.md
Closes #52 
@captain-sal pls merge this PR!
> Introduction to Docker.md

- Documentation on AI-ML.md
> AI-ML Document

- Documentation on API - Avani Mathur.md
Issue #63 
@captain-sal @Nitya-Pasrija
> API Documentation

- AuthO.md
- webSocket.md
> Auth-O Documentation

- webSocket.md
> Documentation on Web-Socket

- documentaion on computer networks #57 by priyamina.md
> Create documentation on computer networks #57 by priyamina.md

- Documentation on Node.js .md
> Documentation on Node.js

- React.js Documentation #84 by priyamina.md
>  React.js Documentation #84 by priyamina.md

- documentation on software development #58 by priyamina.md
>  documentation on software development #58 by priyamina.md

- Documentation on exploring world of data science and analytics #61 by priyamina.md
>  Documentation on exploring world of data science and analytics#61 by priyamina

- array_venusch001.md
Hello team,
I'm pleased to inform you that the documentation on arrays is now complete. It encompasses a detailed explanation of arrays, their usage. I've aimed for clarity and inclusivity, with practical examples for better comprehension. 
Thank you,
[VenusCh001]
issue #78
> arrays documentation VenusCh001

- Documentation on CSS.md
> CSS Documentation

- Documentation on TypesOfCloudServices.md
> Documentation on TypesOfCloudServices

- Comprehensive ES6 JavaScript Documentation #96 by priyamina.md
@captain-sal  please merge this.
>  Comprehensive ES6 JavaScript Documentation #96 by priyamina.md

- Documentation for Web Sockets #81 by priyamina.md
>  Documentation for Web Sockets #81 by priyamina.md
